"""Add field mnemonic

Revision ID: f5f729eebea1
Revises: 7c5a885480a7
Create Date: 2024-11-03 11:29:50.502720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5f729eebea1'
down_revision: Union[str, None] = '7c5a885480a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ethermail_accounts', sa.Column('mnemonic', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ethermail_accounts', 'mnemonic')
    # ### end Alembic commands ###
